# Generated by Django 5.1 on 2024-08-30 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_datetime_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='datetime_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
